//! kohya-ss adapter export proof (milestone 6, issue #17).
//!
//! Builds a one-delta [`LoraAdapters`] set from FIXED constants (no RNG),
//! exports it via [`export_adapters`] in [`ExportFormat::KohyaSs`], reopens the
//! `.safetensors` with the `safetensors` crate directly, and asserts the on-disk
//! form matches a checked-in golden generated by `reference/lora_export_reference.py`:
//!
//! - the three kohya keys (`.lora_down.weight`, `.lora_up.weight`, `.alpha`),
//! - the `.alpha` scalar value,
//! - the transposed `A`/`B` factors (burn `[d_in, d_out]` → kohya `[out, in]`).
//!
//! Always-run, offline, milliseconds. Regenerate the fixture with
//! `just export-reference`.
//!
//! **Convention:** the constants are burn `[d_in, d_out]` layout; the exporter
//! owns the transpose, so the Python reference and this test both compare
//! against the already-transposed golden with zero transposing here.

use burn::backend::NdArray;
use burn::module::Param;
use burn::nn::{DropoutConfig, Linear};
use burn::tensor::{TensorData, Tolerance};
use loractl_core::LoraDelta;
use loractl_core::adapters::LoraAdapters;
use loractl_core::export::{ExportFormat, export_adapters};
use safetensors::SafeTensors;
use std::path::PathBuf;

type TB = NdArray;

// FIXED constants (burn `[d_in, d_out]`, row-major). These MUST match
// `reference/lora_export_reference.py` verbatim — the golden is derived from the
// same numbers. path=transformer.h.0.attn.c_attn, d_in=4, d_out=6, rank=2, alpha=8.
const PATH: &str = "transformer.h.0.attn.c_attn";
const A_INIT: [f32; 8] = [0.10, -0.20, 0.30, 0.40, -0.50, 0.60, 0.70, -0.80]; // [4,2]
const B_INIT: [f32; 12] = [
    0.01, -0.02, 0.03, -0.04, 0.05, -0.06, 0.07, -0.08, 0.09, -0.10, 0.11, -0.12,
]; // [2,6]
const RANK: usize = 2;
const ALPHA: f64 = 8.0;

#[derive(serde::Deserialize)]
struct Golden {
    kohya_keys: Vec<String>,
    alpha_value: f32,
    a_transposed: Vec<f32>,
    a_shape: Vec<usize>,
    b_transposed: Vec<f32>,
    b_shape: Vec<usize>,
}

/// A unique temp dir, removed on drop (same convention as the other tests).
struct TempDir(PathBuf);

impl TempDir {
    fn new(tag: &str) -> Self {
        let nanos = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let dir =
            std::env::temp_dir().join(format!("loractl-{tag}-{}-{nanos}", std::process::id()));
        Self(dir)
    }
}

impl Drop for TempDir {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.0);
    }
}

/// Read a safetensors `TensorView`'s raw little-endian f32 bytes into a `Vec<f32>`.
fn view_f32(view: &safetensors::tensor::TensorView) -> Vec<f32> {
    view.data()
        .chunks_exact(4)
        .map(|b| f32::from_le_bytes([b[0], b[1], b[2], b[3]]))
        .collect()
}

#[test]
fn kohya_export_matches_golden() {
    let golden: Golden = serde_json::from_str(include_str!("golden/lora_export.json"))
        .expect("golden fixture parses");
    let device = Default::default();

    // Build the one-delta set by struct literal so every weight is a fixed
    // constant. scaling = alpha / rank = 8 / 2 = 4.
    let lora_a = Linear::<TB> {
        weight: Param::from_data(TensorData::new(A_INIT.to_vec(), [4, 2]), &device),
        bias: None,
    };
    let lora_b = Linear::<TB> {
        weight: Param::from_data(TensorData::new(B_INIT.to_vec(), [2, 6]), &device),
        bias: None,
    };
    let delta = LoraDelta {
        lora_a,
        lora_b,
        scaling: ALPHA / RANK as f64,
        dropout: DropoutConfig::new(0.0).init(),
    };
    let set = LoraAdapters {
        deltas: vec![delta],
        targets: vec![PATH.to_string()],
    };

    // Export, then reopen the raw file with the safetensors crate directly —
    // exactly how a ComfyUI/Krea LoRA loader reads it.
    let out = TempDir::new("adapter-export");
    let path = out.0.join("adapter.safetensors");
    export_adapters(&set, ExportFormat::KohyaSs, &path).expect("export succeeds");

    let bytes = std::fs::read(&path).expect("read exported file");
    let st = SafeTensors::deserialize(&bytes).expect("valid safetensors");

    // Keys (sorted) must equal the golden's kohya key set.
    let mut names: Vec<String> = st.names().into_iter().map(String::from).collect();
    names.sort();
    let mut want = golden.kohya_keys.clone();
    want.sort();
    assert_eq!(names, want, "on-disk kohya key set");

    let tol = Tolerance::<f32>::absolute(1e-6);

    // .alpha scalar [1] == golden alpha.
    let alpha_key = format!("lora_{}.alpha", PATH.replace('.', "_"));
    let alpha_view = st.tensor(&alpha_key).expect("alpha tensor present");
    assert_eq!(alpha_view.shape(), &[1], "alpha is a [1] scalar");
    let alpha = view_f32(&alpha_view);
    TensorData::new(alpha, [1])
        .assert_approx_eq::<f32>(&TensorData::new(vec![golden.alpha_value], [1]), tol);

    // lora_down = A transposed to [rank, d_in] = [2, 4].
    let down_key = format!("lora_{}.lora_down.weight", PATH.replace('.', "_"));
    let down_view = st.tensor(&down_key).expect("lora_down present");
    assert_eq!(
        down_view.shape(),
        golden.a_shape.as_slice(),
        "lora_down shape"
    );
    TensorData::new(view_f32(&down_view), golden.a_shape.clone())
        .assert_approx_eq::<f32>(&TensorData::new(golden.a_transposed, golden.a_shape), tol);

    // lora_up = B transposed to [d_out, rank] = [6, 2].
    let up_key = format!("lora_{}.lora_up.weight", PATH.replace('.', "_"));
    let up_view = st.tensor(&up_key).expect("lora_up present");
    assert_eq!(up_view.shape(), golden.b_shape.as_slice(), "lora_up shape");
    TensorData::new(view_f32(&up_view), golden.b_shape.clone())
        .assert_approx_eq::<f32>(&TensorData::new(golden.b_transposed, golden.b_shape), tol);
}

/// The golden test above uses exactly one delta, so the `zip(deltas, targets)`
/// loop in `export_adapters` is never exercised with >1 delta — a bug that
/// collided keys or dropped elements would pass. Pin that N deltas produce
/// `3·N` distinct, correctly-named tensors.
#[test]
fn multi_delta_export_writes_distinct_keys_per_target() {
    use std::collections::HashSet;

    let device = Default::default();
    let targets = ["transformer.h.0.attn.c_attn", "transformer.h.1.mlp.c_fc"];
    // Values are irrelevant here (we assert on keys/count, not numerics), so a
    // plain `new` per site is enough; the two deltas differ in shape.
    let deltas = vec![
        LoraDelta::<TB>::new(4, 6, 2, 8.0, 0.0, &device),
        LoraDelta::<TB>::new(8, 5, 3, 6.0, 0.0, &device),
    ];
    let set = LoraAdapters {
        deltas,
        targets: targets.iter().map(|s| s.to_string()).collect(),
    };

    let out = TempDir::new("adapter-export-multi");
    let path = out.0.join("adapter.safetensors");
    export_adapters(&set, ExportFormat::KohyaSs, &path).expect("export succeeds");

    let bytes = std::fs::read(&path).expect("read exported file");
    let st = SafeTensors::deserialize(&bytes).expect("valid safetensors");
    let names: HashSet<String> = st.names().into_iter().map(String::from).collect();

    assert_eq!(
        names.len(),
        6,
        "two deltas must yield 6 distinct tensors, got {names:?}"
    );
    for t in targets {
        let base = format!("lora_{}", t.replace('.', "_"));
        assert!(
            names.contains(&format!("{base}.lora_down.weight")),
            "missing lora_down for {t}"
        );
        assert!(
            names.contains(&format!("{base}.lora_up.weight")),
            "missing lora_up for {t}"
        );
        assert!(
            names.contains(&format!("{base}.alpha")),
            "missing alpha for {t}"
        );
    }
}
