//! Deterministic numerics proof for the rectified-flow objective (issue #19, M8).
//!
//! This test reproduces a fully-deterministic flow-matching toy — fixed
//! weights, fixed "noise", fixed timesteps, no RNG anywhere — and asserts the
//! timestep sampler transform, the interpolation/velocity-target conventions,
//! the resolution-dependent shift, and a 20-step v-prediction training run
//! against a checked-in golden fixture generated by a PyTorch reference
//! (`reference/flow_reference.py`). Because every value is a fixed constant,
//! PyTorch and burn compute the *identical* arithmetic sequence and differ only
//! by f32 rounding, so a tight absolute tolerance is meaningful.
//!
//! Always-run, offline, milliseconds — it reads the golden JSON via
//! `include_str!` (no Python, no network at `cargo test` time). Regenerate the
//! fixture with `just flow-reference` when the toy constants or the pinned
//! torch version change.
//!
//! **Convention:** all matrices are in burn's `[d_in, d_out]` layout. The Python
//! reference owns *all* transpose handling (torch `Linear.weight` is `[out, in]`),
//! so this test compares burn tensors to the golden with zero transposing.
//! Time convention: t = 0 is DATA, t = 1 is NOISE (SD3/diffusers/kohya), and the
//! v-prediction target is `ε − x_0` (noise minus data).

use burn::backend::{Autodiff, NdArray};
use burn::module::Param;
use burn::nn::{DropoutConfig, Linear};
use burn::optim::{GradientsParams, Optimizer, SgdConfig};
use burn::tensor::{Tensor, TensorData, Tolerance};
use loractl_core::config::FlowConfig;
use loractl_core::{LoraLinear, LoraMlp, flow};

/// Plain CPU backend for the pure-math (sampler/interp) sections.
type TB = NdArray;
/// Autodiff-wrapped CPU backend for the training-loop section.
type AB = Autodiff<NdArray>;

// FIXED constants (burn `[d_in, d_out]`, row-major). These MUST match
// `reference/flow_reference.py` verbatim — the golden fixture is derived from
// the same numbers. latent_dim=3, hidden=4, rank=2, alpha=4 (=> scaling=2),
// lr=0.1, N=20, batch=4; the velocity net's input is concat[x_t, t] (width 4).
const W1: [f32; 16] = [
    0.30, -0.20, 0.45, 0.10, -0.25, 0.35, -0.15, 0.40, 0.20, 0.15, -0.30, -0.35, 0.50, -0.40, 0.25,
    0.30,
]; // [4,4] frozen fc1 weight
const B1: [f32; 4] = [0.10, -0.15, 0.20, 0.05]; // [4] frozen fc1 bias
const W_BASE: [f32; 12] = [
    0.1, -0.2, 0.3, 0.4, 0.5, -0.6, -0.7, 0.8, 0.9, 0.15, -0.25, 0.35,
]; // [4,3] frozen readout base
const A_INIT: [f32; 8] = [0.2, 0.1, -0.3, 0.4, 0.5, -0.6, 0.7, 0.8]; // [4,2] trainable
const X0: [f32; 12] = [
    1.5, -0.6, 0.8, -1.2, 0.9, -0.4, 0.3, -1.0, 1.1, -0.7, 0.5, -1.3,
]; // [4,3] data points
const EPS: [f32; 12] = [
    0.4, 1.1, -0.9, -0.5, -1.4, 0.7, 1.2, 0.2, -0.6, -0.3, 0.8, 1.0,
]; // [4,3] fixed "noise"
const T_INTERP: [f32; 4] = [0.15, 0.4, 0.65, 0.9]; // [4] fixed timesteps
const U: [f32; 8] = [-2.5, -1.0, -0.3, 0.0, 0.4, 1.0, 2.0, 3.0]; // raw normal draws

/// Sampler config (a): the SD3 defaults + the kohya/SD3-scheduler shift.
/// MUST match the golden's `sampler_symmetric`.
const SYMMETRIC: FlowConfig = FlowConfig {
    logit_mean: 0.0,
    logit_std: 1.0,
    shift: 3.0,
};
/// Sampler config (b): deliberately asymmetric (mean 0.5, std 2.0, shift 1.5)
/// so a `sigmoid(-u)` or mean-sign error cannot cancel the way it would at the
/// symmetric defaults. MUST match the golden's `sampler_asymmetric`.
const ASYMMETRIC: FlowConfig = FlowConfig {
    logit_mean: 0.5,
    logit_std: 2.0,
    shift: 1.5,
};

#[derive(serde::Deserialize)]
struct Golden {
    sampler: SamplerGolden,
    resolution_shift: Vec<ResolutionCase>,
    interp: InterpGolden,
    train: TrainGolden,
}

#[derive(serde::Deserialize)]
struct SamplerGolden {
    symmetric: SymmetricGolden,
    asymmetric: AsymmetricGolden,
}

#[derive(serde::Deserialize)]
struct SymmetricGolden {
    t_sigmoid: Vec<f32>,
    t_shifted: Vec<f32>,
}

#[derive(serde::Deserialize)]
struct AsymmetricGolden {
    t_shifted: Vec<f32>,
}

#[derive(serde::Deserialize)]
struct ResolutionCase {
    seq_len: usize,
    shift: f64,
}

#[derive(serde::Deserialize)]
struct InterpGolden {
    x_t: Vec<f32>,
    v_target: Vec<f32>,
}

#[derive(serde::Deserialize)]
struct TrainGolden {
    fc1_weight_final: Vec<f32>,
    fc1_bias_final: Vec<f32>,
    base_final: Vec<f32>,
    lora_a_final: Vec<f32>,
    lora_b_final: Vec<f32>,
    losses: Vec<f32>,
}

fn golden() -> Golden {
    serde_json::from_str(include_str!("golden/flow_toy.json")).expect("golden fixture parses")
}

/// f32 unit roundoff ~6e-8; the measured torch-vs-numpy divergence over the
/// 20-step toy is ~2.4e-7 (see `reference/flow_reference.py`'s stderr report),
/// and burn's sigmoid differs from torch's by ~1e-7 — so 1e-5 leaves ample
/// margin. Documented fallback: bump to absolute(1e-4) if a different CI BLAS
/// flakes.
fn tol() -> Tolerance<f32> {
    Tolerance::<f32>::absolute(1e-5)
}

#[test]
fn timestep_sampler_matches_reference() {
    let g = golden();
    let device = Default::default();

    // (a) `shift_timesteps` in isolation, fed the golden's INTERMEDIATE
    // sigmoid output — localizes a shift-transform bug away from the sigmoid.
    let t_sigmoid = Tensor::<TB, 1>::from_data(
        TensorData::new(g.sampler.symmetric.t_sigmoid.clone(), [8]),
        &device,
    );
    flow::shift_timesteps(t_sigmoid, SYMMETRIC.shift)
        .into_data()
        .assert_approx_eq::<f32>(
            &TensorData::new(g.sampler.symmetric.t_shifted.clone(), [8]),
            tol(),
        );

    // (a) the FULL `logit_to_t` composition fed the raw normal draws — this is
    // the exact transform `sample_timesteps` feeds its RNG draws into.
    let u = Tensor::<TB, 1>::from_data(TensorData::new(U.to_vec(), [8]), &device);
    flow::logit_to_t(u.clone(), SYMMETRIC)
        .into_data()
        .assert_approx_eq::<f32>(&TensorData::new(g.sampler.symmetric.t_shifted, [8]), tol());

    // (b) the asymmetric config through the full composition only.
    flow::logit_to_t(u, ASYMMETRIC)
        .into_data()
        .assert_approx_eq::<f32>(&TensorData::new(g.sampler.asymmetric.t_shifted, [8]), tol());
}

#[test]
fn resolution_shift_matches_reference() {
    // f64 in both Python and Rust computing the same μ line + exp — the golden
    // values reproduce to within a few ulps, so 1e-12 is generous.
    for case in golden().resolution_shift {
        let got = flow::resolution_shift(case.seq_len);
        assert!(
            (got - case.shift).abs() < 1e-12,
            "resolution_shift({}) = {got}, golden {}",
            case.seq_len,
            case.shift
        );
    }
    // Endpoint anchors, exact by construction of the μ line: the returned value
    // is the LINEAR shift exp(μ), NOT μ itself (the μ-vs-exp(μ) confusion guard).
    assert!((flow::resolution_shift(256) - 0.5f64.exp()).abs() < 1e-12);
    assert!((flow::resolution_shift(4096) - 1.15f64.exp()).abs() < 1e-12);
}

#[test]
fn interpolation_and_velocity_target_match_reference() {
    let g = golden();
    let device = Default::default();

    let x0 = Tensor::<TB, 2>::from_data(TensorData::new(X0.to_vec(), [4, 3]), &device);
    let eps = Tensor::<TB, 2>::from_data(TensorData::new(EPS.to_vec(), [4, 3]), &device);
    let t = Tensor::<TB, 1>::from_data(TensorData::new(T_INTERP.to_vec(), [4]), &device);

    // x_t = (1 − t)·x_0 + t·ε — t = 0 is DATA, t = 1 is NOISE.
    flow::interpolate(x0.clone(), eps.clone(), t)
        .into_data()
        .assert_approx_eq::<f32>(&TensorData::new(g.interp.x_t, [4, 3]), tol());

    // v = ε − x_0 (noise minus data) — the sign convention under test.
    flow::velocity_target(x0, eps)
        .into_data()
        .assert_approx_eq::<f32>(&TensorData::new(g.interp.v_target, [4, 3]), tol());
}

#[test]
fn training_matches_pytorch_reference() {
    let g = golden();
    let device = Default::default();

    // Build the velocity net by struct literal so every weight is a fixed
    // constant (Param::from_data auto-marks require_grad; frozen layers are
    // then explicitly un-marked). The net IS a LoraMlp: frozen random-feature
    // projection + LoRA readout, input concat[x_t, t], output = predicted v.
    let fc1 = Linear::<AB> {
        weight: Param::from_data(TensorData::new(W1.to_vec(), [4, 4]), &device)
            .set_require_grad(false),
        bias: Some(
            Param::from_data(TensorData::new(B1.to_vec(), [4]), &device).set_require_grad(false),
        ),
    };
    let base = Linear::<AB> {
        weight: Param::from_data(TensorData::new(W_BASE.to_vec(), [4, 3]), &device)
            .set_require_grad(false),
        bias: None,
    };
    let lora_a = Linear::<AB> {
        weight: Param::from_data(TensorData::new(A_INIT.to_vec(), [4, 2]), &device),
        bias: None,
    };
    let lora_b = Linear::<AB> {
        weight: Param::from_data(TensorData::new(vec![0.0f32; 6], [2, 3]), &device),
        bias: None,
    };
    let mut model = LoraMlp {
        fc1,
        fc2: LoraLinear {
            base,
            lora_a,
            lora_b,
            scaling: 2.0, // alpha/rank = 4/2
            dropout: DropoutConfig::new(0.0).init(),
        },
    };

    // Training data built through the SAME golden-pinned helpers the trainer
    // routes through — never inline (1−t)/ε−x₀ arithmetic. The t column of the
    // input is the same tensor fed to `interpolate`.
    let x0 = Tensor::<AB, 2>::from_data(TensorData::new(X0.to_vec(), [4, 3]), &device);
    let eps = Tensor::<AB, 2>::from_data(TensorData::new(EPS.to_vec(), [4, 3]), &device);
    let t = Tensor::<AB, 1>::from_data(TensorData::new(T_INTERP.to_vec(), [4]), &device);
    let x_t = flow::interpolate(x0.clone(), eps.clone(), t.clone());
    let v_target = flow::velocity_target(x0, eps);
    let t_col: Tensor<AB, 2> = t.unsqueeze_dim(1);
    let input = Tensor::cat(vec![x_t, t_col], 1); // [4,4] = concat[x_t, t]

    // Plain SGD: all-None config => update is exactly `p - lr*grad`, byte-for-byte
    // the torch.optim.SGD(momentum=0, dampening=0, weight_decay=0) rule.
    let mut optim = SgdConfig::new().init::<AB, LoraMlp<AB>>();

    let mut losses = Vec::with_capacity(20);
    for _ in 0..20 {
        let pred = model.forward(input.clone());
        let diff = pred - v_target.clone();
        // Plain MSE with weighting ≡ 1.0, identical to the reference's
        // ((pred - v)**2).mean() — the logit-normal scheme's t/(1−t) emphasis
        // lives in the sampling density, never a multiplicative loss weight.
        let loss = diff.clone().mul(diff).mean();
        // Record BEFORE backward/step — the order must match the Python loop.
        losses.push(loss.clone().into_scalar());
        let grads = GradientsParams::from_grads(loss.backward(), &model);
        model = optim.step(0.1, model, grads);
    }

    TensorData::new(losses, [20])
        .assert_approx_eq::<f32>(&TensorData::new(g.train.losses, [20]), tol());
    model
        .fc2
        .lora_a
        .weight
        .val()
        .into_data()
        .assert_approx_eq::<f32>(&TensorData::new(g.train.lora_a_final, [4, 2]), tol());
    model
        .fc2
        .lora_b
        .weight
        .val()
        .into_data()
        .assert_approx_eq::<f32>(&TensorData::new(g.train.lora_b_final, [2, 3]), tol());

    // The frozen layers must be provably, bit-exactly unchanged after 20 steps.
    let strict = Tolerance::<f32>::strict();
    model
        .fc1
        .weight
        .val()
        .into_data()
        .assert_approx_eq::<f32>(&TensorData::new(g.train.fc1_weight_final, [4, 4]), strict);
    model
        .fc1
        .bias
        .as_ref()
        .expect("fc1 has a bias")
        .val()
        .into_data()
        .assert_approx_eq::<f32>(&TensorData::new(g.train.fc1_bias_final, [4]), strict);
    model
        .fc2
        .base
        .weight
        .val()
        .into_data()
        .assert_approx_eq::<f32>(&TensorData::new(g.train.base_final, [4, 3]), strict);
}
