//! Deterministic numerics proof for the LoRA adapter (issue #1, criterion 3).
//!
//! This test reproduces a fully-deterministic single-[`LoraLinear`] toy — fixed
//! weights, fixed inputs, no RNG anywhere — and asserts its trained `lora_a`,
//! `lora_b`, and per-step losses against a checked-in golden fixture generated by
//! a PyTorch reference (`reference/lora_reference.py`). Because every value is a
//! fixed constant, PyTorch and burn compute the *identical* arithmetic sequence
//! and differ only by f32 rounding, so a tight absolute tolerance is meaningful.
//!
//! Always-run, offline, milliseconds — it reads the golden JSON via `include_str!`
//! (no Python, no network at `cargo test` time). Regenerate the fixture with
//! `just reference` when the toy constants or the pinned torch version change.
//!
//! **Convention:** all matrices are in burn's `[d_in, d_out]` layout. The Python
//! reference owns *all* transpose handling (torch `Linear.weight` is `[out, in]`),
//! so this test compares burn tensors to the golden with zero transposing.

use burn::backend::{Autodiff, NdArray};
use burn::module::Param;
use burn::nn::Linear;
use burn::optim::{GradientsParams, Optimizer, SgdConfig};
use burn::tensor::{Tensor, TensorData, Tolerance};
use loractl_core::LoraLinear;

type AB = Autodiff<NdArray>;

// FIXED constants (burn `[d_in, d_out]`, row-major). These MUST match
// `reference/lora_reference.py` verbatim — the golden fixture is derived from the
// same numbers. d_in=4, d_out=3, rank=2, alpha=2 (=> scaling=1), lr=0.1, N=20.
const W_BASE: [f32; 12] = [
    0.1, -0.2, 0.3, 0.4, 0.5, -0.6, -0.7, 0.8, 0.9, 0.15, -0.25, 0.35,
]; // [4,3] frozen base
const A_INIT: [f32; 8] = [0.2, 0.1, -0.3, 0.4, 0.5, -0.6, 0.7, 0.8]; // [4,2] trainable
const X: [f32; 20] = [
    1.0, 0.5, -0.5, 0.25, -1.0, 0.3, 0.8, -0.2, 0.6, -0.7, 0.9, 0.1, 0.2, 0.4, -0.1, 1.0, -0.4,
    0.6, 0.3, -0.8,
]; // [5,4]
const T: [f32; 15] = [
    0.5, -0.5, 1.0, 1.0, 0.0, -1.0, -0.3, 0.7, 0.2, 0.9, -0.1, 0.4, 0.1, 0.6, -0.6,
]; // [5,3]

#[derive(serde::Deserialize)]
struct Golden {
    lora_a_final: Vec<f32>,
    lora_b_final: Vec<f32>,
    base_final: Vec<f32>,
    losses: Vec<f32>,
}

#[test]
fn matches_pytorch_reference() {
    let golden: Golden =
        serde_json::from_str(include_str!("golden/lora_toy.json")).expect("golden fixture parses");
    let device = Default::default();

    // Build the toy by struct literal so every weight is a fixed constant
    // (Param::from_data auto-marks require_grad; the base is then frozen).
    let base = Linear::<AB> {
        weight: Param::from_data(TensorData::new(W_BASE.to_vec(), [4, 3]), &device)
            .set_require_grad(false),
        bias: None,
    };
    let lora_a = Linear::<AB> {
        weight: Param::from_data(TensorData::new(A_INIT.to_vec(), [4, 2]), &device),
        bias: None,
    };
    let lora_b = Linear::<AB> {
        weight: Param::from_data(TensorData::new(vec![0.0f32; 6], [2, 3]), &device),
        bias: None,
    };
    let mut model = LoraLinear {
        base,
        lora_a,
        lora_b,
        scaling: 1.0, // alpha/rank = 2/2
    };

    let x = Tensor::<AB, 2>::from_data(TensorData::new(X.to_vec(), [5, 4]), &device);
    let t = Tensor::<AB, 2>::from_data(TensorData::new(T.to_vec(), [5, 3]), &device);

    // Plain SGD: all-None config => update is exactly `p - lr*grad`, byte-for-byte
    // the torch.optim.SGD(momentum=0, dampening=0, weight_decay=0) rule.
    let mut optim = SgdConfig::new().init::<AB, LoraLinear<AB>>();

    let mut losses = Vec::with_capacity(20);
    for _ in 0..20 {
        let pred = model.forward(x.clone());
        let diff = pred - t.clone();
        // Manual MSE, identical to the reference's ((pred-t)**2).mean().
        let loss = diff.clone().mul(diff).mean();
        // Record BEFORE backward/step — the order must match the Python loop.
        losses.push(loss.clone().into_scalar());
        let grads = GradientsParams::from_grads(loss.backward(), &model);
        model = optim.step(0.1, model, grads);
    }

    // Tolerance: f32 unit roundoff ~6e-8; over 20 steps of O(1) values with
    // differing ndarray-vs-libtorch summation order the accumulated abs error
    // lands ~1e-7 on this machine (measured), so 1e-5 leaves ample margin.
    // Documented fallback: bump to absolute(1e-4) if a different CI BLAS flakes.
    let tol = Tolerance::<f32>::absolute(1e-5);

    TensorData::new(losses, [20])
        .assert_approx_eq::<f32>(&TensorData::new(golden.losses, [20]), tol);
    model
        .lora_a
        .weight
        .val()
        .into_data()
        .assert_approx_eq::<f32>(&TensorData::new(golden.lora_a_final, [4, 2]), tol);
    model
        .lora_b
        .weight
        .val()
        .into_data()
        .assert_approx_eq::<f32>(&TensorData::new(golden.lora_b_final, [2, 3]), tol);
    // The frozen base must be provably, bit-exactly unchanged after 20 steps.
    model.base.weight.val().into_data().assert_approx_eq::<f32>(
        &TensorData::new(golden.base_final, [4, 3]),
        Tolerance::<f32>::strict(),
    );
}
