//! Opt-in staged parity against the **real** Krea-2-Raw MMDiT weights
//! (M11, #22 acceptance: real weights load with `errors`/`missing` empty +
//! forward parity on genuine weights).
//!
//! **Depth-truncated by design:** the full 28-block model in f32 is ~53 GB —
//! beyond a 48 GiB host — so this proof runs the REAL WIDTHS (6144 features,
//! 48/12 heads, the full text-fusion transformer, every component type) at
//! `layers = 2`, loading the matching subset of `raw.safetensors`. The
//! reference golden is generated by the official `mmdit.py` over the *same*
//! truncated state, so the comparison is exact. Full-depth runs arrive with
//! M13's quantized/bf16 path.
//!
//! Gated behind the `mmdit-real` feature AND `#[ignore]`; fixtures come from:
//!
//! ```sh
//! just mmdit-real-reference   # downloads raw.safetensors (26.3 GB) once,
//!                             # dumps the truncated f32 fixture + golden
//! just test-mmdit-real        # runs THIS test (release build)
//! ```
#![cfg(feature = "mmdit-real")]

use burn::backend::NdArray;
use burn::tensor::{Tensor, TensorData};
use loractl_core::mmdit::{Mmdit, MmditConfig};
use serde::Deserialize;
use std::path::Path;

type B = NdArray;

const SAFETENSORS: &str = "tests/fixtures/mmdit-real/model.safetensors";
const GOLDEN: &str = "tests/fixtures/mmdit_real_golden.json";

#[derive(Deserialize)]
struct GoldenConfig {
    layers: usize,
    txtdim: usize,
    features: usize,
}

#[derive(Deserialize)]
struct Golden {
    config: GoldenConfig,
    txtmask: Vec<i64>,
    t: Vec<f32>,
    img_tokens: Vec<f32>,
    img_tokens_shape: Vec<usize>,
    context: Vec<f32>,
    context_shape: Vec<usize>,
    pos: Vec<f32>,
    pos_shape: Vec<usize>,
    safetensors_keys: Vec<String>,
    after_txtfusion: Vec<f32>,
    output: Vec<f32>,
    output_shape: Vec<usize>,
}

fn max_abs_diff(a: &[f32], b: &[f32]) -> f32 {
    assert_eq!(a.len(), b.len(), "length mismatch");
    a.iter()
        .zip(b)
        .map(|(x, y)| (x - y).abs())
        .fold(0.0f32, f32::max)
}

fn cosine(a: &[f32], b: &[f32]) -> f64 {
    let dot: f64 = a.iter().zip(b).map(|(x, y)| *x as f64 * *y as f64).sum();
    let na: f64 = a.iter().map(|x| (*x as f64).powi(2)).sum::<f64>().sqrt();
    let nb: f64 = b.iter().map(|x| (*x as f64).powi(2)).sum::<f64>().sqrt();
    dot / (na * nb)
}

/// Zero a flat `[1, l, d]` stage at positions whose mask entry is 0 (the
/// masked-position contract shared with the reference).
fn zero_masked(stage: &mut [f32], mask: &[f32], d: usize) {
    for (i, &m) in mask.iter().enumerate() {
        if m == 0.0 {
            stage[i * d..(i + 1) * d].fill(0.0);
        }
    }
}

#[test]
#[ignore = "opt-in: needs the real Krea-2-Raw fixtures produced by `just mmdit-real-reference` (26 GB download + torch)"]
fn real_mmdit_truncated_forward_matches_krea2_golden() {
    use burn_store::{KeyRemapper, ModuleSnapshot, PyTorchToBurnAdapter, SafetensorsStore};

    for f in [SAFETENSORS, GOLDEN] {
        if !Path::new(f).exists() {
            panic!(
                "real mmdit fixture missing ({f}).\n\
                 Generate them first with:  just mmdit-real-reference"
            );
        }
    }

    let golden: Golden =
        serde_json::from_str(&std::fs::read_to_string(GOLDEN).unwrap()).expect("parse real golden");
    let config = MmditConfig::krea2_truncated(golden.config.layers);
    assert_eq!(golden.config.features, config.features);
    assert_eq!(golden.config.txtdim, config.txtdim);

    let device = Default::default();
    let mut model = Mmdit::<B>::init(config, &device);
    let remapper =
        KeyRemapper::from_patterns(Mmdit::<B>::key_remap().to_vec()).expect("valid remap patterns");
    let mut store = SafetensorsStore::from_file(SAFETENSORS)
        .remap(remapper)
        .with_from_adapter(PyTorchToBurnAdapter);
    let result = model.load_from(&mut store).expect("safetensors load");

    // Acceptance (#22): the real weights map cleanly.
    assert!(result.errors.is_empty(), "load errors: {:?}", result.errors);
    assert!(
        result.missing.is_empty(),
        "unexpected missing params: {:?}",
        result.missing
    );
    assert_eq!(
        result.applied.len(),
        golden.safetensors_keys.len(),
        "expected all {} truncated-checkpoint tensors applied, got {}",
        golden.safetensors_keys.len(),
        result.applied.len()
    );

    let s = &golden.img_tokens_shape;
    let img = Tensor::<B, 1>::from_data(
        TensorData::new(golden.img_tokens.clone(), [golden.img_tokens.len()]),
        &device,
    )
    .reshape([s[0], s[1], s[2]]);
    let c = &golden.context_shape;
    let context = Tensor::<B, 1>::from_data(
        TensorData::new(golden.context.clone(), [golden.context.len()]),
        &device,
    )
    .reshape([c[0], c[1], c[2], c[3]]);
    let t = Tensor::<B, 1>::from_data(TensorData::new(golden.t.clone(), [golden.t.len()]), &device);
    let p = &golden.pos_shape;
    let pos = Tensor::<B, 1>::from_data(
        TensorData::new(golden.pos.clone(), [golden.pos.len()]),
        &device,
    )
    .reshape([p[0], p[1], p[2]]);
    let mut mask: Vec<f32> = golden.txtmask.iter().map(|&m| m as f32).collect();
    let txtmask: Vec<f32> = mask.clone();
    mask.extend(std::iter::repeat_n(1.0f32, s[1]));
    let l = mask.len();
    let mask = Tensor::<B, 1>::from_data(TensorData::new(mask, [l]), &device).reshape([1, l]);

    let trace = model.forward_trace(img, context, t, pos, mask);

    // The fused text (all non-block components) and the final output — the
    // two ends of the graph; the tiny test already localizes per-stage.
    let mut after_txtfusion = trace
        .after_txtfusion
        .into_data()
        .convert::<f32>()
        .into_vec::<f32>()
        .unwrap();
    zero_masked(&mut after_txtfusion, &txtmask, golden.config.txtdim);
    let fusion_diff = max_abs_diff(&after_txtfusion, &golden.after_txtfusion);
    let fusion_cos = cosine(&after_txtfusion, &golden.after_txtfusion);
    eprintln!("real txtfusion: max|Δ| = {fusion_diff:e}, cosine = {fusion_cos:.8}");

    assert_eq!(trace.output.dims().to_vec(), golden.output_shape);
    let output = trace
        .output
        .into_data()
        .convert::<f32>()
        .into_vec::<f32>()
        .unwrap();
    let out_diff = max_abs_diff(&output, &golden.output);
    let out_cos = cosine(&output, &golden.output);
    eprintln!("real output: max|Δ| = {out_diff:e}, cosine = {out_cos:.8}");

    // Real-scale accumulation drift; the cosine backstops are the claim.
    assert!(
        fusion_diff <= 2e-2,
        "txtfusion max|Δ| = {fusion_diff:e} exceeds 2e-2"
    );
    assert!(
        out_diff <= 2e-2,
        "output max|Δ| = {out_diff:e} exceeds 2e-2"
    );
    assert!(fusion_cos > 0.9999, "txtfusion cosine {fusion_cos}");
    assert!(out_cos > 0.9999, "output cosine {out_cos}");
}
