//! Offline forward parity + LoRA attach for the Krea 2 MMDiT (M11, #22).
//!
//! A real `SingleStreamDiT` at a tiny fixed config (seed 11) — generated by
//! the OFFICIAL `krea-ai/krea-2` `mmdit.py` at a pinned commit — was dumped to
//! `tests/fixtures/tiny-mmdit/model.safetensors` with staged goldens in
//! `tests/fixtures/mmdit_tiny_golden.json` (regenerate with
//! `just mmdit-reference`). This test loads those same weights into
//! [`loractl_core::Mmdit`] and asserts the staged forward reproduces the
//! golden, fully offline — including the reference's pad-to-256 path (the
//! tiny combined sequence is 22 tokens) and a masked text token.
//!
//! **Masked-position contract:** positions blocked by the mask (the padded
//! tail, the masked text token) carry attention garbage that never leaks
//! into valid outputs and whose exact value is backend-dependent. The
//! reference zeroes them in the dumped stages; this test zeroes its own
//! stages with the same masks before comparing.
//!
//! The second test proves the M6 LoRA attach on the trunk (issue #22's
//! acceptance c): zero-init adapters are a bit-identical no-op, and one real
//! training step routes gradients to the adapters only.

use burn::backend::{Autodiff, NdArray};
use burn::tensor::{Tensor, TensorData};
use loractl_core::adapters::LoraAdapters;
use loractl_core::lora::LoraDelta;
use loractl_core::mmdit::{Mmdit, MmditConfig};
use serde::Deserialize;

/// Plain (no-autodiff) CPU backend for the parity check.
type B = NdArray;
/// Autodiff-wrapped backend for the training-step check.
type AB = Autodiff<NdArray>;

const GOLDEN: &str = include_str!("fixtures/mmdit_tiny_golden.json");
const SAFETENSORS: &str = "tests/fixtures/tiny-mmdit/model.safetensors";

#[derive(Deserialize)]
struct GoldenConfig {
    features: usize,
    tdim: usize,
    txtdim: usize,
    heads: usize,
    kvheads: usize,
    multiplier: usize,
    layers: usize,
    patch: usize,
    channels: usize,
    txtheads: usize,
    txtkvheads: usize,
    txtlayers: usize,
}

#[derive(Deserialize)]
struct Golden {
    config: GoldenConfig,
    txtmask: Vec<i64>,
    t: Vec<f32>,
    img_tokens: Vec<f32>,
    img_tokens_shape: Vec<usize>,
    context: Vec<f32>,
    context_shape: Vec<usize>,
    pos: Vec<f32>,
    pos_shape: Vec<usize>,
    safetensors_keys: Vec<String>,
    after_first: Vec<f32>,
    tvec: Vec<f32>,
    after_txtfusion: Vec<f32>,
    after_txtmlp: Vec<f32>,
    after_block0: Vec<f32>,
    after_block0_shape: Vec<usize>,
    output: Vec<f32>,
    output_shape: Vec<usize>,
}

fn max_abs_diff(a: &[f32], b: &[f32]) -> f32 {
    assert_eq!(
        a.len(),
        b.len(),
        "length mismatch: {} vs {}",
        a.len(),
        b.len()
    );
    a.iter()
        .zip(b)
        .map(|(x, y)| (x - y).abs())
        .fold(0.0f32, f32::max)
}

fn assert_stage(name: &str, got: &[f32], want: &[f32], tol: f32) {
    let diff = max_abs_diff(got, want);
    assert!(diff <= tol, "{name}: max|Δ| = {diff:e} exceeds tol {tol:e}",);
    eprintln!("{name}: max|Δ| = {diff:e} (tol {tol:e})");
}

fn flatten<Bk: burn::tensor::backend::Backend, const D: usize>(t: Tensor<Bk, D>) -> Vec<f32> {
    t.into_data().convert::<f32>().into_vec::<f32>().unwrap()
}

fn cosine(a: &[f32], b: &[f32]) -> f64 {
    let dot: f64 = a.iter().zip(b).map(|(x, y)| *x as f64 * *y as f64).sum();
    let na: f64 = a.iter().map(|x| (*x as f64).powi(2)).sum::<f64>().sqrt();
    let nb: f64 = b.iter().map(|x| (*x as f64).powi(2)).sum::<f64>().sqrt();
    dot / (na * nb)
}

fn argmax(v: &[f32]) -> usize {
    v.iter()
        .enumerate()
        .max_by(|(_, a), (_, b)| a.partial_cmp(b).unwrap())
        .unwrap()
        .0
}

/// Zero a flat `[1, l, d]` stage at positions whose mask entry is 0.
fn zero_masked(stage: &mut [f32], mask: &[f32], d: usize) {
    for (i, &m) in mask.iter().enumerate() {
        if m == 0.0 {
            stage[i * d..(i + 1) * d].fill(0.0);
        }
    }
}

/// Load the tiny MMDiT fixture, asserting a clean mapping.
fn load_tiny<Bk: burn::tensor::backend::Backend>(expected_tensors: usize) -> Mmdit<Bk> {
    use burn_store::{KeyRemapper, ModuleSnapshot, PyTorchToBurnAdapter, SafetensorsStore};

    let device = Default::default();
    let mut model = Mmdit::<Bk>::init(MmditConfig::tiny(), &device);

    // Sequential-index + `mod`-keyword renames, then the nn.Linear transpose.
    let remapper = KeyRemapper::from_patterns(Mmdit::<Bk>::key_remap().to_vec())
        .expect("valid remap patterns");
    let mut store = SafetensorsStore::from_file(SAFETENSORS)
        .remap(remapper)
        .with_from_adapter(PyTorchToBurnAdapter);
    let result = model.load_from(&mut store).expect("safetensors load");

    assert!(result.errors.is_empty(), "load errors: {:?}", result.errors);
    assert!(
        result.missing.is_empty(),
        "unexpected missing params: {:?}",
        result.missing
    );
    assert_eq!(
        result.applied.len(),
        expected_tensors,
        "expected all {} fixture tensors applied, got {}",
        expected_tensors,
        result.applied.len()
    );
    model
}

/// The golden's inputs as tensors: (img_tokens, context, t, pos, mask).
#[allow(clippy::type_complexity)]
fn golden_inputs<Bk: burn::tensor::backend::Backend>(
    golden: &Golden,
    device: &Bk::Device,
) -> (
    Tensor<Bk, 3>,
    Tensor<Bk, 4>,
    Tensor<Bk, 1>,
    Tensor<Bk, 3>,
    Tensor<Bk, 2>,
) {
    let s = &golden.img_tokens_shape;
    let img = Tensor::<Bk, 1>::from_data(
        TensorData::new(golden.img_tokens.clone(), [golden.img_tokens.len()]),
        device,
    )
    .reshape([s[0], s[1], s[2]]);
    let c = &golden.context_shape;
    let context = Tensor::<Bk, 1>::from_data(
        TensorData::new(golden.context.clone(), [golden.context.len()]),
        device,
    )
    .reshape([c[0], c[1], c[2], c[3]]);
    let t = Tensor::<Bk, 1>::from_data(TensorData::new(golden.t.clone(), [golden.t.len()]), device);
    let p = &golden.pos_shape;
    let pos = Tensor::<Bk, 1>::from_data(
        TensorData::new(golden.pos.clone(), [golden.pos.len()]),
        device,
    )
    .reshape([p[0], p[1], p[2]]);
    // Combined 0/1 key mask: the golden's text mask + all-ones image tokens.
    let mut mask: Vec<f32> = golden.txtmask.iter().map(|&m| m as f32).collect();
    mask.extend(std::iter::repeat_n(1.0f32, s[1]));
    let l = mask.len();
    let mask = Tensor::<Bk, 1>::from_data(TensorData::new(mask, [l]), device).reshape([1, l]);
    (img, context, t, pos, mask)
}

#[test]
fn tiny_mmdit_forward_matches_krea2_golden() {
    let golden: Golden = serde_json::from_str(GOLDEN).expect("parse golden json");
    let config = MmditConfig::tiny();

    // Config-drift guard: the fixture was generated at exactly the Rust tiny
    // config.
    let g = &golden.config;
    assert_eq!(
        (
            g.features,
            g.tdim,
            g.txtdim,
            g.heads,
            g.kvheads,
            g.multiplier
        ),
        (
            config.features,
            config.tdim,
            config.txtdim,
            config.heads,
            config.kvheads,
            config.multiplier
        )
    );
    assert_eq!(
        (
            g.layers,
            g.patch,
            g.channels,
            g.txtheads,
            g.txtkvheads,
            g.txtlayers
        ),
        (
            config.layers,
            config.patch,
            config.channels,
            config.txtheads,
            config.txtkvheads,
            config.txtlayers
        )
    );

    let device = Default::default();
    let model = load_tiny::<B>(golden.safetensors_keys.len());
    let (img, context, t, pos, mask) = golden_inputs::<B>(&golden, &device);

    let trace = model.forward_trace(img, context, t, pos, mask);

    let tol = 1e-4f32;
    let txtmask: Vec<f32> = golden.txtmask.iter().map(|&m| m as f32).collect();

    assert_stage(
        "after_first",
        &flatten(trace.after_first),
        &golden.after_first,
        tol,
    );
    assert_stage("tvec", &flatten(trace.tvec), &golden.tvec, tol);

    // Text stages: zero the masked text token on the Rust side (the golden
    // is dumped pre-zeroed — the masked-position contract).
    let mut after_txtfusion = flatten(trace.after_txtfusion);
    zero_masked(&mut after_txtfusion, &txtmask, golden.config.txtdim);
    assert_stage(
        "after_txtfusion",
        &after_txtfusion,
        &golden.after_txtfusion,
        tol,
    );
    let mut after_txtmlp = flatten(trace.after_txtmlp);
    zero_masked(&mut after_txtmlp, &txtmask, golden.config.features);
    assert_stage("after_txtmlp", &after_txtmlp, &golden.after_txtmlp, tol);

    // Trunk stage: zero everything the padded combined mask blocks.
    assert_eq!(
        trace.after_block0.dims().to_vec(),
        golden.after_block0_shape,
        "padded combined length must match (pad-to-256)"
    );
    let padded_len = golden.after_block0_shape[1];
    let mut padmask = txtmask.clone();
    padmask.extend(std::iter::repeat_n(1.0f32, golden.img_tokens_shape[1]));
    padmask.extend(std::iter::repeat_n(0.0f32, padded_len - padmask.len()));
    let mut after_block0 = flatten(trace.after_block0);
    zero_masked(&mut after_block0, &padmask, golden.config.features);
    assert_stage("after_block0", &after_block0, &golden.after_block0, tol);

    // The final velocity prediction over the image tokens — all valid.
    assert_eq!(trace.output.dims().to_vec(), golden.output_shape);
    let output = flatten(trace.output);
    assert_stage("output", &output, &golden.output, tol);

    // Tolerance-free backstops.
    assert_eq!(
        argmax(&output),
        argmax(&golden.output),
        "output argmax must match the golden"
    );
    let cos = cosine(&output, &golden.output);
    assert!(cos > 0.99999, "output cosine {cos} must exceed 0.99999");
    eprintln!("output cosine = {cos:.8}");
}

#[test]
fn lora_attach_one_step_on_loaded_mmdit() {
    use burn::module::Module;
    use burn::nn::loss::{MseLoss, Reduction};
    use burn::optim::{AdamConfig, GradientsParams, Optimizer};

    let golden: Golden = serde_json::from_str(GOLDEN).expect("parse golden json");
    let device = Default::default();
    // Freeze the base: adapters ride on an unmodified model (standard LoRA).
    let model = load_tiny::<AB>(golden.safetensors_keys.len()).no_grad();
    let (img, context, t, pos, mask) = golden_inputs::<AB>(&golden, &device);

    // The advertised sites cover every trunk projection; delta EVERY one of
    // them (all 7 site kinds × all blocks), so a wiring bug at any single
    // site — not just wq — breaks the zero-init no-op or the grad routing.
    let sites = model.injectable_sites();
    assert_eq!(sites.len(), golden.config.layers * 7);
    let mut set = LoraAdapters::<AB> {
        deltas: sites
            .iter()
            .map(|s| LoraDelta::new(s.d_in, s.d_out, 4, 8.0, 0.0, &device))
            .collect(),
        targets: sites.iter().map(|s| s.path.clone()).collect(),
    };

    // Zero-init B ⇒ the fully-adapted forward equals the base golden exactly.
    let adapted = model.forward_with_adapters(
        img.clone(),
        context.clone(),
        t.clone(),
        pos.clone(),
        mask.clone(),
        &set,
    );
    assert_stage(
        "zero-init adapted output (all sites)",
        &flatten(adapted),
        &golden.output,
        1e-4,
    );

    // One real step: MSE of the velocity prediction against zeros.
    let out = model.forward_with_adapters(img, context, t, pos, mask, &set);
    let loss = MseLoss::new().forward(out.clone(), out.zeros_like(), Reduction::Mean);
    let loss_value: f32 = loss.clone().into_scalar();
    assert!(loss_value.is_finite(), "loss must be finite: {loss_value}");

    let grads = loss.backward();
    // EVERY delta must be in the graph...
    for (delta, target) in set.deltas.iter().zip(&set.targets) {
        assert!(
            delta.lora_b.weight.val().grad(&grads).is_some(),
            "LoRA `B` at {target} must receive a gradient"
        );
        assert!(
            delta.lora_a.weight.val().grad(&grads).is_some(),
            "LoRA `A` at {target} must receive a gradient"
        );
    }
    // ...and the frozen base gets nothing (spot checks across site kinds).
    let block = &model.blocks[0];
    assert!(block.attn.wq.weight.val().grad(&grads).is_none());
    assert!(block.attn.wo.weight.val().grad(&grads).is_none());
    assert!(block.mlp.down.weight.val().grad(&grads).is_none());

    let mut optim = AdamConfig::new().init::<AB, LoraAdapters<AB>>();
    let grad_params = GradientsParams::from_grads(grads, &set);
    set = optim.step(1e-3, set, grad_params);
    for (delta, target) in set.deltas.iter().zip(&set.targets) {
        let b_sum: f32 = delta.lora_b.weight.val().abs().sum().into_scalar();
        assert!(
            b_sum > 0.0,
            "after one step the LoRA `B` at {target} must have moved off zero"
        );
    }
}
