# /// script
# requires-python = ">=3.10"
# dependencies = ["torch==2.*", "einops", "safetensors", "numpy", "requests"]
# ///
"""Krea 2 MMDiT PyTorch reference for loractl M11 (issue #22) forward parity.

The denoiser has no pip package: the authoritative implementation is
`krea-ai/krea-2`'s `mmdit.py` (plus `sampling.py`'s `prepare()` for the
position/mask construction). This script downloads that exact source at a
PINNED COMMIT into a temp dir and imports it, so the golden is generated by
the real reference code rather than a hand-copied (drift-prone) re-implementation.
Network is needed only at fixture-REGENERATION time — the emitted fixture +
golden are checked in and the Rust test runs offline.

Tiny mode: a real `SingleStreamDiT` at a tiny config with seeded random
weights; dumps the safetensors + staged goldens (post-patchify input, tvec,
text-fusion output, per-stage trunk states, final sliced output) for a fixed
latent/context/t. The combined sequence is shorter than 256, so the
reference's pad-to-256 path fires — the port must reproduce it.

--real mode: a DEPTH-TRUNCATED real-width model (layers=2) loading the
matching subset of krea/Krea-2-Raw's raw.safetensors (26.3 GB bf16; the full
28-block model in f32 is ~53 GB — beyond this machine's RAM, so full-depth
parity is deferred to the M13 quantized path; see issue #22). Proves the
real-weights load path and real-scale numerics on genuine weights across
every component type.
"""

import argparse
import json
import os
import platform
import sys
import tempfile
import urllib.request

# The reference decorates several forwards with @torch.compile(fullgraph=True)
# (a CUDA-oriented optimization); disable dynamo so they run eagerly on CPU.
os.environ.setdefault("TORCHDYNAMO_DISABLE", "1")

import torch  # noqa: E402

KREA2_COMMIT = "cf3c9102c924168699b90d97a2cb15059d761488"
KREA2_RAW = f"https://raw.githubusercontent.com/krea-ai/krea-2/{KREA2_COMMIT}"

# Tiny architecture — real SingleStreamDiT structure at minimal dims.
# Duplicated in the Rust tiny config (MmditConfig::tiny()). headdim =
# features/heads = 16 -> rope axes [4, 6, 6]; SwiGLU mlpdim =
# round_up(int(2*96/3)*4, 128) = 256; txt SwiGLU = round_up(int(2*40/3)*4, 128)
# = 128. GQA in the trunk (6 heads / 2 kv), none in text fusion (2/2) — like
# the real config (48/12 and 20/20).
#
# Deliberately NON-DEGENERATE: features/2 (48), kv_out (32), txtdim (40),
# head_dim (16), layers (2) and txtlayers (3) are all pairwise distinct, so a
# port that derives one width from the wrong config field (or conflates trunk
# depth with the fusion projector's layer axis) fails this always-run fixture
# instead of only the opt-in real one.
TINY = dict(
    features=96,
    tdim=16,
    txtdim=40,
    heads=6,
    kvheads=2,
    multiplier=4,
    layers=2,
    patch=2,
    channels=4,
    txtheads=2,
    txtkvheads=2,
    txtlayers=3,
)
TINY_LATENT = 8  # latent grid 8x8 -> 4x4 = 16 image tokens
TINY_TXTLEN = 6  # text tokens (one masked, to exercise the key mask)

# The real config (inference.py `single_mmdit_large_wide`), depth-truncated
# for the --real staged proof.
REAL = dict(
    features=6144,
    tdim=256,
    txtdim=2560,
    heads=48,
    kvheads=12,
    multiplier=4,
    layers=2,  # truncated from 28 — full depth exceeds this machine's RAM in f32
    patch=2,
    channels=16,
    txtheads=20,
    txtkvheads=20,
    txtlayers=12,
)
REAL_LATENT = 16  # 16x16 latent -> 8x8 = 64 image tokens
REAL_TXTLEN = 8


def fetch_krea2(tmp: str):
    """Download mmdit.py + sampling.py at the pinned commit and import mmdit."""
    for name in ("mmdit.py", "sampling.py"):
        with urllib.request.urlopen(f"{KREA2_RAW}/{name}") as r:
            body = r.read()
        with open(os.path.join(tmp, name), "wb") as f:
            f.write(body)
    sys.path.insert(0, tmp)
    import mmdit  # noqa: PLC0415

    # The reference pins SDPA to the CUDA-only cuDNN kernel
    # (`sdpa_kernel(SDPBackend.CUDNN_ATTENTION)`), which has no CPU backend.
    # Swap in the SAME math without the kernel pin — numerically this is
    # plain scaled_dot_product_attention, identical semantics.
    from einops import rearrange

    def cpu_attention(q, k, v, mask=None, scale=None, gqa=False):
        x = torch.nn.functional.scaled_dot_product_attention(
            q, k, v, attn_mask=mask, scale=scale, enable_gqa=gqa
        )
        return rearrange(x, "B H L D -> B L (H D)")

    mmdit.attention = cpu_attention
    return mmdit


def prepare(img, txtlen, patch, txtmask):
    """sampling.py's prepare(), inlined (it imports PIL at module scope)."""
    from einops import rearrange, repeat

    b, _, h, w = img.shape
    h_, w_ = h // patch, w // patch
    imgids = torch.zeros((h_, w_, 3), device=img.device)
    imgids[..., 1] = torch.arange(h_, device=img.device)[:, None]
    imgids[..., 2] = torch.arange(w_, device=img.device)[None, :]
    imgpos = repeat(imgids, "h w three -> b (h w) three", b=b, three=3)
    imgmask = torch.ones(b, h_ * w_, device=img.device, dtype=torch.bool)
    img = rearrange(img, "b c (h ph) (w pw) -> b (h w) (c ph pw)", ph=patch, pw=patch)

    txtpos = torch.zeros(b, txtlen, 3, device=img.device)
    mask = torch.cat((txtmask, imgmask), dim=1)
    pos = torch.cat((txtpos, imgpos), dim=1)
    return img, pos, mask


def staged_forward(model, img_tokens, context, t, pos, mask):
    """model.forward with stage capture via hooks.

    Masked positions (the padded tail of the 256-aligned combined sequence,
    and masked text tokens) are ZEROED in the dumped stages: their values are
    attention garbage that never leaks into valid outputs (they are blocked
    as keys), and the exact garbage is SDPA-backend-dependent (a fully-masked
    query row is NaN on some backends). The Rust parity test zeroes its own
    stages with the same masks before comparing — that is the contract.
    """
    stages = {}

    def grab(name):
        def hook(_m, _i, out):
            stages[name] = (out[0] if isinstance(out, tuple) else out).detach().clone()

        return hook

    handles = [
        model.first.register_forward_hook(grab("after_first")),
        model.tproj.register_forward_hook(grab("tvec")),
        model.txtfusion.register_forward_hook(grab("after_txtfusion")),
        model.txtmlp.register_forward_hook(grab("after_txtmlp")),
        model.blocks[0].register_forward_hook(grab("after_block0")),
    ]
    try:
        with torch.no_grad():
            out = model(img=img_tokens, context=context, t=t, pos=pos, mask=mask)
    finally:
        for h in handles:
            h.remove()
    stages["output"] = out

    txtlen = context.shape[1]
    txtmask = mask[:, :txtlen]
    padlen = stages["after_block0"].shape[1]
    padmask = torch.nn.functional.pad(mask, (0, padlen - mask.shape[1]), value=False)
    zero = lambda x, m: torch.where(m.unsqueeze(-1), x, torch.zeros_like(x))  # noqa: E731
    stages["after_txtfusion"] = zero(stages["after_txtfusion"], txtmask)
    stages["after_txtmlp"] = zero(stages["after_txtmlp"], txtmask)
    stages["after_block0"] = zero(stages["after_block0"], padmask)
    return stages


def dump(path, tensors, extra):
    golden = dict(extra)
    for name, tsr in tensors.items():
        golden[name] = tsr.float().flatten().tolist()
        golden[f"{name}_shape"] = list(tsr.shape)
    with open(path, "w") as f:
        json.dump(golden, f)
    print(f"golden written to {path}", file=sys.stderr)


def run(
    mmdit, cfg_dict, latent_hw, txtlen, out_dir, fixture_name, golden_name, state=None
):
    config = mmdit.SingleMMDiTConfig(**cfg_dict)
    with torch.device("meta") if state is not None else torch.device("cpu"):
        model = mmdit.SingleStreamDiT(config)
    if state is not None:
        model.load_state_dict(state, strict=True, assign=True)
        model = model.float()
    model = model.eval()

    save_dir = os.path.join(out_dir, fixture_name)
    os.makedirs(save_dir, exist_ok=True)
    from safetensors.torch import save_file

    sd = {k: v.contiguous() for k, v in model.state_dict().items()}
    save_file(sd, os.path.join(save_dir, "model.safetensors"))

    b = 1
    latent = torch.rand(b, cfg_dict["channels"], latent_hw, latent_hw) * 2 - 1
    txtmask = torch.ones(b, txtlen, dtype=torch.bool)
    txtmask[0, -1] = False  # one masked text position: the key mask must bite
    img_tokens, pos, mask = prepare(latent, txtlen, cfg_dict["patch"], txtmask)
    context = torch.randn(b, txtlen, cfg_dict["txtlayers"], cfg_dict["txtdim"])
    t = torch.full((b,), 0.5)

    stages = staged_forward(model, img_tokens, context, t, pos, mask)

    dump(
        os.path.join(out_dir, golden_name),
        {
            "latent": latent,
            "img_tokens": img_tokens,
            "context": context,
            "pos": pos,
            **stages,
        },
        {
            "config": cfg_dict,
            "txtmask": txtmask.long().flatten().tolist(),
            "t": t.tolist(),
            "krea2_commit": KREA2_COMMIT,
            "safetensors_keys": sorted(sd.keys()),
            "provenance": {
                "torch": torch.__version__,
                "python": sys.version.split()[0],
                "platform": platform.platform(),
            },
        },
    )
    print(f"mmdit fixture saved to {save_dir} ({len(sd)} tensors)", file=sys.stderr)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", default="crates/loractl-core/tests/fixtures")
    parser.add_argument("--real", action="store_true")
    parser.add_argument(
        "--raw",
        default=None,
        help="path to a local raw.safetensors for --real (downloaded if absent)",
    )
    args = parser.parse_args()
    torch.manual_seed(11)  # M11

    with tempfile.TemporaryDirectory() as tmp:
        mmdit = fetch_krea2(tmp)

        if not args.real:
            run(
                mmdit,
                TINY,
                TINY_LATENT,
                TINY_TXTLEN,
                args.out,
                "tiny-mmdit",
                "mmdit_tiny_golden.json",
            )
            return

        # --real: depth-truncated real-width model over the genuine weights.
        raw = args.raw
        if raw is None:
            from urllib.request import urlretrieve

            raw = os.path.join(args.out, "krea2-raw", "raw.safetensors")
            os.makedirs(os.path.dirname(raw), exist_ok=True)
            if not os.path.exists(raw):
                print("downloading raw.safetensors (26.3 GB)…", file=sys.stderr)
                urlretrieve(
                    "https://huggingface.co/krea/Krea-2-Raw/resolve/main/raw.safetensors",
                    raw,
                )
        from safetensors import safe_open

        # Keep every non-block tensor + blocks 0..REAL['layers']-1, renamed as-is.
        state = {}
        with safe_open(raw, framework="pt") as f:
            for k in f.keys():
                if k.startswith("blocks."):
                    layer = int(k.split(".")[1])
                    if layer >= REAL["layers"]:
                        continue
                state[k] = f.get_tensor(k)
        run(
            mmdit,
            REAL,
            REAL_LATENT,
            REAL_TXTLEN,
            args.out,
            "mmdit-real",
            "mmdit_real_golden.json",
            state=state,
        )


if __name__ == "__main__":
    main()
